# Generated by Django 5.1.6 on 2025-02-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
